### ISSUE TITLE
Font imported in CSS file flagged as unused

### ISSUE THREAD

**Issue by Soviut** [stauren/vite-plugin-deadfile#26]
I have the following `index.css` file that imports a local font file.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  @font-face {
    font-family: 'Inter';
    font-style: normal;
    font-weight: 100 900;
    font-display: swap;
    src: url('../fonts/Inter-VariableFont_opsz,wght.ttf') format('truetype');
  }
}
```

This gets imported into my `main.tsx`

```tsx
import '@/assets/css/index.css'
import App from './App'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
)
```

But `Inter-VariableFont_opsz,wght.ttf` is flagged as unused.
